### PR TITLE
Model selection

### PR DESCRIPTION
**Pull request by Sgarc-027**
Sikandar and I finished writing up the main.py script as well as making necessary changes in the model_sel.py script. We've tested the main.py script and it ran for all feature selection methods. Now we must determine the initial parameters to tune for the grid search.

### CODE REVIEW

**Review by patmasid — COMMENTED** [review]
For file main.py, when you are doing 

```poll_data = data.PollDataProxy(remove_nan=True, convert_to_float=True)```

Don't use remove_nan=True because we do not want to remove all nans. For some features, Nans could represent another category. So maybe you should change it to remove_nan="False".

**Comment by tommy-waltmann** [comment]
Make sure to merge master into this branch and resolve all merge conflicts, I still need to review this and will get to it later today. Reviewing is hard when the diff is messed up, so merge master into this branch, and then I can do a better review

**Comment by tommy-waltmann** [comment]
I have looked things over. Is it fair to say that we have gotten the features that each feature selection method has chosen as the best?

**Comment by tommy-waltmann** [comment]
Also, please removed the pycache and dot files that have been committed. I don't know how those got there, they are in our gitignore.

**Comment by patmasid** [comment]
> I have looked things over. Is it fair to say that we have gotten the features that each feature selection method has chosen as the best?

If you set the num_features in the list to be a small number, then yes, all the features selected will be among first few from all the methods

**Comment by patmasid** [comment]
> > I have looked things over. Is it fair to say that we have gotten the features that each feature selection method has chosen as the best?
> 
> If you set the num_features in the list to be a small number, then yes, all the features selected will be among first few from all the methods

 I checked a few decision trees, and it seems age is one of the very dominant features in all of those trees.  I guess, finding uncorrelated feature also helps a bit because it does not select very similar features for the tree giving more insight into the tree. My personal opinion is 
1. to select either one method or none at all. 
2. And even if combine features from different methods, only few should be selected, like maximum 5 - 8, not more than that. Otherwise, it would select features which have less importance in all of the methods. 
3. Or another way is to select first few features from all methods. (this has not yet been implemented).
4. Also, we can try to go over the questions again and see if there are any more questions which can be removed manually. for example Q27 asks for whether someone voted in some previous elections. It is again kind of asking them directly whether they vote or not. Probably we can remove that question as well. because in the decision trees without any feature selection, this feature is very prominant.

**Pull request merged**
